name: IllitMoney
version: 1.0.1
main: ru.illit.money.IllitMoneyPlugin
api-version: "1.20"
author: Illit
softdepend: [PlaceholderAPI, Vault]
commands:
  pay:
    description: Отправить валюту игроку
    usage: /pay <ник> <сумма>
  balance:
    description: Посмотреть баланс
    usage: /balance [ник]
    aliases: [bal, money]
  baltop:
    description: Топ по балансу
    usage: /baltop
  illit:
    description: Админ-команды Illit
    usage: /illit money ...
permissions:
  illit.money.admin:
    default: op
